# coding: utf-8

"""
    Go Sidecar Accelerator

    This is a sample API written to become a Sidecar leveraging the Gin Go framework.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: tristan.leonard1@ibm.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.models_health_check_response import ModelsHealthCheckResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsHealthCheckResponse(unittest.TestCase):
    """ModelsHealthCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelsHealthCheckResponse(self):
        """Test ModelsHealthCheckResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.models_health_check_response.ModelsHealthCheckResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
