# coding: utf-8

"""
    Go Sidecar Accelerator

    This is a sample API written to become a Sidecar leveraging the Gin Go framework.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: tristan.leonard1@ibm.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Go Sidecar Accelerator",
    author_email="tristan.leonard1@ibm.com",
    url="",
    keywords=["Swagger", "Go Sidecar Accelerator"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is a sample API written to become a Sidecar leveraging the Gin Go framework.  # noqa: E501
    """
)
