# coding: utf-8

# flake8: noqa
"""
    Go Sidecar Accelerator

    This is a sample API written to become a Sidecar leveraging the Gin Go framework.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: tristan.leonard1@ibm.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.all_ofmodels_file_data_metadata import AllOfmodelsFileDataMetadata
from swagger_client.models.models_file_data import ModelsFileData
from swagger_client.models.models_file_metadata import ModelsFileMetadata
from swagger_client.models.models_health_check_response import ModelsHealthCheckResponse
