# coding: utf-8

"""
    Go Sidecar Accelerator

    This is a sample API written to become a Sidecar leveraging the Gin Go framework.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: tristan.leonard1@ibm.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModelsFileMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content_type': 'str',
        'file_name': 'str',
        'size': 'int',
        'version': 'str'
    }

    attribute_map = {
        'content_type': 'contentType',
        'file_name': 'fileName',
        'size': 'size',
        'version': 'version'
    }

    def __init__(self, content_type=None, file_name=None, size=None, version=None):  # noqa: E501
        """ModelsFileMetadata - a model defined in Swagger"""  # noqa: E501
        self._content_type = None
        self._file_name = None
        self._size = None
        self._version = None
        self.discriminator = None
        if content_type is not None:
            self.content_type = content_type
        if file_name is not None:
            self.file_name = file_name
        if size is not None:
            self.size = size
        if version is not None:
            self.version = version

    @property
    def content_type(self):
        """Gets the content_type of this ModelsFileMetadata.  # noqa: E501

        @Description the file content type  # noqa: E501

        :return: The content_type of this ModelsFileMetadata.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this ModelsFileMetadata.

        @Description the file content type  # noqa: E501

        :param content_type: The content_type of this ModelsFileMetadata.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    @property
    def file_name(self):
        """Gets the file_name of this ModelsFileMetadata.  # noqa: E501

        @Description the file name  # noqa: E501

        :return: The file_name of this ModelsFileMetadata.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this ModelsFileMetadata.

        @Description the file name  # noqa: E501

        :param file_name: The file_name of this ModelsFileMetadata.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def size(self):
        """Gets the size of this ModelsFileMetadata.  # noqa: E501

        @Description the size of the file in bytes  # noqa: E501

        :return: The size of this ModelsFileMetadata.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this ModelsFileMetadata.

        @Description the size of the file in bytes  # noqa: E501

        :param size: The size of this ModelsFileMetadata.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def version(self):
        """Gets the version of this ModelsFileMetadata.  # noqa: E501

        @Description the file version  # noqa: E501

        :return: The version of this ModelsFileMetadata.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ModelsFileMetadata.

        @Description the file version  # noqa: E501

        :param version: The version of this ModelsFileMetadata.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelsFileMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsFileMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
